// <auto-generated />
namespace LZRNS.DomainModels.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updateplayer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateplayer));
        
        string IMigrationMetadata.Id
        {
            get { return "201810180841381_update-player"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
