// <auto-generated />
namespace LZRNS.DomainModels.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updateplayerperteamstats : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateplayerperteamstats));
        
        string IMigrationMetadata.Id
        {
            get { return "201908291130408_update-playerperteam-stats"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
